# Generated by Django 2.2.8 on 2019-12-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdataset',
            name='local_machine_guid',
            field=models.CharField(default='noop', max_length=36),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='clientdataset',
            constraint=models.UniqueConstraint(fields=('local_machine_guid',), name='localmachienguidunique'),
        ),
    ]
