# Generated by Django 2.2.8 on 2019-12-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_slug',
            field=models.SlugField(max_length=64),
        ),
    ]
